/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TaiLieuRouteImport } from './routes/tai-lieu'
import { Route as ReviewMonHocRouteImport } from './routes/review-mon-hoc'
import { Route as ReviewGiangVienRouteImport } from './routes/review-giang-vien'
import { Route as PostsRouteImport } from './routes/posts'
import { Route as GocTamLinhRouteImport } from './routes/goc-tam-linh'
import { Route as DeThiRouteImport } from './routes/de-thi'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TaiLieuIdRouteImport } from './routes/tai-lieu.$id'
import { Route as ReviewMonHocIdRouteImport } from './routes/review-mon-hoc.$id'
import { Route as ReviewGiangVienIdRouteImport } from './routes/review-giang-vien.$id'
import { Route as PostsIdRouteImport } from './routes/posts.$id'
import { Route as DeThiIdRouteImport } from './routes/de-thi.$id'

const TaiLieuRoute = TaiLieuRouteImport.update({
  id: '/tai-lieu',
  path: '/tai-lieu',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewMonHocRoute = ReviewMonHocRouteImport.update({
  id: '/review-mon-hoc',
  path: '/review-mon-hoc',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewGiangVienRoute = ReviewGiangVienRouteImport.update({
  id: '/review-giang-vien',
  path: '/review-giang-vien',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsRoute = PostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => rootRouteImport,
} as any)
const GocTamLinhRoute = GocTamLinhRouteImport.update({
  id: '/goc-tam-linh',
  path: '/goc-tam-linh',
  getParentRoute: () => rootRouteImport,
} as any)
const DeThiRoute = DeThiRouteImport.update({
  id: '/de-thi',
  path: '/de-thi',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TaiLieuIdRoute = TaiLieuIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => TaiLieuRoute,
} as any)
const ReviewMonHocIdRoute = ReviewMonHocIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ReviewMonHocRoute,
} as any)
const ReviewGiangVienIdRoute = ReviewGiangVienIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ReviewGiangVienRoute,
} as any)
const PostsIdRoute = PostsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PostsRoute,
} as any)
const DeThiIdRoute = DeThiIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DeThiRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/de-thi': typeof DeThiRouteWithChildren
  '/goc-tam-linh': typeof GocTamLinhRoute
  '/posts': typeof PostsRouteWithChildren
  '/review-giang-vien': typeof ReviewGiangVienRouteWithChildren
  '/review-mon-hoc': typeof ReviewMonHocRouteWithChildren
  '/tai-lieu': typeof TaiLieuRouteWithChildren
  '/de-thi/$id': typeof DeThiIdRoute
  '/posts/$id': typeof PostsIdRoute
  '/review-giang-vien/$id': typeof ReviewGiangVienIdRoute
  '/review-mon-hoc/$id': typeof ReviewMonHocIdRoute
  '/tai-lieu/$id': typeof TaiLieuIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/de-thi': typeof DeThiRouteWithChildren
  '/goc-tam-linh': typeof GocTamLinhRoute
  '/posts': typeof PostsRouteWithChildren
  '/review-giang-vien': typeof ReviewGiangVienRouteWithChildren
  '/review-mon-hoc': typeof ReviewMonHocRouteWithChildren
  '/tai-lieu': typeof TaiLieuRouteWithChildren
  '/de-thi/$id': typeof DeThiIdRoute
  '/posts/$id': typeof PostsIdRoute
  '/review-giang-vien/$id': typeof ReviewGiangVienIdRoute
  '/review-mon-hoc/$id': typeof ReviewMonHocIdRoute
  '/tai-lieu/$id': typeof TaiLieuIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/de-thi': typeof DeThiRouteWithChildren
  '/goc-tam-linh': typeof GocTamLinhRoute
  '/posts': typeof PostsRouteWithChildren
  '/review-giang-vien': typeof ReviewGiangVienRouteWithChildren
  '/review-mon-hoc': typeof ReviewMonHocRouteWithChildren
  '/tai-lieu': typeof TaiLieuRouteWithChildren
  '/de-thi/$id': typeof DeThiIdRoute
  '/posts/$id': typeof PostsIdRoute
  '/review-giang-vien/$id': typeof ReviewGiangVienIdRoute
  '/review-mon-hoc/$id': typeof ReviewMonHocIdRoute
  '/tai-lieu/$id': typeof TaiLieuIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/de-thi'
    | '/goc-tam-linh'
    | '/posts'
    | '/review-giang-vien'
    | '/review-mon-hoc'
    | '/tai-lieu'
    | '/de-thi/$id'
    | '/posts/$id'
    | '/review-giang-vien/$id'
    | '/review-mon-hoc/$id'
    | '/tai-lieu/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/de-thi'
    | '/goc-tam-linh'
    | '/posts'
    | '/review-giang-vien'
    | '/review-mon-hoc'
    | '/tai-lieu'
    | '/de-thi/$id'
    | '/posts/$id'
    | '/review-giang-vien/$id'
    | '/review-mon-hoc/$id'
    | '/tai-lieu/$id'
  id:
    | '__root__'
    | '/'
    | '/de-thi'
    | '/goc-tam-linh'
    | '/posts'
    | '/review-giang-vien'
    | '/review-mon-hoc'
    | '/tai-lieu'
    | '/de-thi/$id'
    | '/posts/$id'
    | '/review-giang-vien/$id'
    | '/review-mon-hoc/$id'
    | '/tai-lieu/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DeThiRoute: typeof DeThiRouteWithChildren
  GocTamLinhRoute: typeof GocTamLinhRoute
  PostsRoute: typeof PostsRouteWithChildren
  ReviewGiangVienRoute: typeof ReviewGiangVienRouteWithChildren
  ReviewMonHocRoute: typeof ReviewMonHocRouteWithChildren
  TaiLieuRoute: typeof TaiLieuRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tai-lieu': {
      id: '/tai-lieu'
      path: '/tai-lieu'
      fullPath: '/tai-lieu'
      preLoaderRoute: typeof TaiLieuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review-mon-hoc': {
      id: '/review-mon-hoc'
      path: '/review-mon-hoc'
      fullPath: '/review-mon-hoc'
      preLoaderRoute: typeof ReviewMonHocRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review-giang-vien': {
      id: '/review-giang-vien'
      path: '/review-giang-vien'
      fullPath: '/review-giang-vien'
      preLoaderRoute: typeof ReviewGiangVienRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts': {
      id: '/posts'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof PostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goc-tam-linh': {
      id: '/goc-tam-linh'
      path: '/goc-tam-linh'
      fullPath: '/goc-tam-linh'
      preLoaderRoute: typeof GocTamLinhRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/de-thi': {
      id: '/de-thi'
      path: '/de-thi'
      fullPath: '/de-thi'
      preLoaderRoute: typeof DeThiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tai-lieu/$id': {
      id: '/tai-lieu/$id'
      path: '/$id'
      fullPath: '/tai-lieu/$id'
      preLoaderRoute: typeof TaiLieuIdRouteImport
      parentRoute: typeof TaiLieuRoute
    }
    '/review-mon-hoc/$id': {
      id: '/review-mon-hoc/$id'
      path: '/$id'
      fullPath: '/review-mon-hoc/$id'
      preLoaderRoute: typeof ReviewMonHocIdRouteImport
      parentRoute: typeof ReviewMonHocRoute
    }
    '/review-giang-vien/$id': {
      id: '/review-giang-vien/$id'
      path: '/$id'
      fullPath: '/review-giang-vien/$id'
      preLoaderRoute: typeof ReviewGiangVienIdRouteImport
      parentRoute: typeof ReviewGiangVienRoute
    }
    '/posts/$id': {
      id: '/posts/$id'
      path: '/$id'
      fullPath: '/posts/$id'
      preLoaderRoute: typeof PostsIdRouteImport
      parentRoute: typeof PostsRoute
    }
    '/de-thi/$id': {
      id: '/de-thi/$id'
      path: '/$id'
      fullPath: '/de-thi/$id'
      preLoaderRoute: typeof DeThiIdRouteImport
      parentRoute: typeof DeThiRoute
    }
  }
}

interface DeThiRouteChildren {
  DeThiIdRoute: typeof DeThiIdRoute
}

const DeThiRouteChildren: DeThiRouteChildren = {
  DeThiIdRoute: DeThiIdRoute,
}

const DeThiRouteWithChildren = DeThiRoute._addFileChildren(DeThiRouteChildren)

interface PostsRouteChildren {
  PostsIdRoute: typeof PostsIdRoute
}

const PostsRouteChildren: PostsRouteChildren = {
  PostsIdRoute: PostsIdRoute,
}

const PostsRouteWithChildren = PostsRoute._addFileChildren(PostsRouteChildren)

interface ReviewGiangVienRouteChildren {
  ReviewGiangVienIdRoute: typeof ReviewGiangVienIdRoute
}

const ReviewGiangVienRouteChildren: ReviewGiangVienRouteChildren = {
  ReviewGiangVienIdRoute: ReviewGiangVienIdRoute,
}

const ReviewGiangVienRouteWithChildren = ReviewGiangVienRoute._addFileChildren(
  ReviewGiangVienRouteChildren,
)

interface ReviewMonHocRouteChildren {
  ReviewMonHocIdRoute: typeof ReviewMonHocIdRoute
}

const ReviewMonHocRouteChildren: ReviewMonHocRouteChildren = {
  ReviewMonHocIdRoute: ReviewMonHocIdRoute,
}

const ReviewMonHocRouteWithChildren = ReviewMonHocRoute._addFileChildren(
  ReviewMonHocRouteChildren,
)

interface TaiLieuRouteChildren {
  TaiLieuIdRoute: typeof TaiLieuIdRoute
}

const TaiLieuRouteChildren: TaiLieuRouteChildren = {
  TaiLieuIdRoute: TaiLieuIdRoute,
}

const TaiLieuRouteWithChildren =
  TaiLieuRoute._addFileChildren(TaiLieuRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DeThiRoute: DeThiRouteWithChildren,
  GocTamLinhRoute: GocTamLinhRoute,
  PostsRoute: PostsRouteWithChildren,
  ReviewGiangVienRoute: ReviewGiangVienRouteWithChildren,
  ReviewMonHocRoute: ReviewMonHocRouteWithChildren,
  TaiLieuRoute: TaiLieuRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
